config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :goals do
      resources :requirements
    end
  end
  devise_for :users
  root to: "projects#index"
  get 'dependencies/create'

  get '/projects/:project_id/goals/:goal_id/graph', to: 'goals#graph'
  get '/tasks/search', to: 'tasks#search'
  post '/tasks/:id/complete', to: 'tasks#complete', as: 'complete_task'
  resources :tasks
  resource :dependencies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dependency.rb
class Dependency < ApplicationRecord
  belongs_to :dependent_task, class_name: 'Task'
  belongs_to :resolved_task, class_name: 'Task'
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :project

  has_many :requirements
  has_many :tasks, through: :requirements

  def next_tasks
    tasks.map(&:next_tasks).uniq
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :goals
end

app/models/requirement.rb
class Requirement < ApplicationRecord
  belongs_to :goal
  belongs_to :task
end

app/models/task.rb
module Enumerable
  def find_yield(fallback=nil) #:yield:
    each do |member|
      result = yield(member)
      return result if result
    end
    fallback
  end
end

class Task < ApplicationRecord
  has_many :requirements
  has_many :goals, through: :requirements

  has_many :dependencies, :foreign_key => :resolved_task_id
  has_many :dependents, class_name: 'Dependency', :foreign_key => :dependent_task_id

  has_many :dependency_tasks, :through => :dependencies, :source => :dependent_task
  has_many :dependent_tasks, :through => :dependents, :source => :resolved_task

  scope :complete, -> { where(:completed => true) }
  scope :incomplete, -> { where(:completed => false) }

  scope :active, -> { incomplete.where(:archived => false) }

  def next_task
    # find the leaf node of the dependencies
    dependency_tasks.active.find_yield { |task| task.next_task } || self
  end

  def next_tasks
    # find the leaf node of the dependencies
    result = dependency_tasks.active.flat_map { |task| task.next_tasks } || self

    if result.length > 0
      result
    else
      [self]
    end
  end

  def as_json(*args)
    super(*args).merge({dependency_count: dependency_count})
  end

  def graph
    {
      :nodes => nodes,
      :edges => edges
    }
  end

  def edges
    [
      dependencies.map { |d| { from: d.dependent_task_id, to: d.resolved_task_id } },
      dependency_tasks.map(&:edges),
    ].flatten.uniq
  end

  def nodes
    if dependency_count == 0
      [self]
    end

    ([self] + dependency_tasks.flat_map(&:nodes)).uniq
  end

  def dependency_count
    if dependency_tasks.incomplete.empty?
      0
    else
      1 + dependency_tasks.incomplete.sum(&:dependency_count)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise *[
    :database_authenticatable,
    (:registerable unless Rails.env.production?),
    :recoverable,
    :rememberable,
    :trackable,
    :validatable
  ].compact

  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation])
  end
end

app/controllers/dependencies_controller.rb
class DependenciesController < ApplicationController
  def create
    dep_params = params.require(:dependency).permit(:dependent_task_id, :resolved_task_id)

    Dependency.create!(dep_params)

    head :ok
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def create
    goal = project.goals.create!(goal_params)

    redirect_to project
  end

  def graph
    render json: goal.tasks.map(&:graph).reduce(&:merge)
  end

  private

  def goal_params
    params.require(:goal).permit(:name)
  end

  def goal
    @goal ||= Goal.find(params[:goal_id])
  end

  def project
    @project ||= Project.find(params[:project_id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include ProjectsHelper

  def index
  end

  def new
  end

  def create
    redirect_to current_user.projects.create!(project_params)
  end

  def show
  end

  private

  def project_params
    params.require(:project).permit(:name)
  end
end

app/controllers/requirements_controller.rb
class RequirementsController < ApplicationController
  def create
    goal.requirements.create!(requirement_params)
  end

  private

  def goal
    @goal ||= Goal.find(params[:goal_id])
  end

  def requirement_params
    params.require(:requirement).permit(:task_id)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  include TasksHelper

  def index
  end

  def show
  end

  def edit
  end

  def update
    task.update!(task_params)

    redirect_to(task)
  end

  def create
    task = Task.create!(task_params)

    redirect_to(task)
  end

  def complete
    task.update!(:completed => !task.completed)

    redirect_back(fallback_location: task_path(task))
  end

  def search
    query = "%#{params[:q]}%"
    name = Task.arel_table[:name]
    description = Task.arel_table[:description]

    tasks = Task
      .active
      .where(name.matches(query))
      .or(Task.where(description.matches(query)))

    render json: tasks.map { |task| {html: render_to_string(task), json: render_to_string(json: task)} }
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :completed, :archived)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dependencies_helper.rb
module DependenciesHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def project
    @project ||= Project.find(params[:id])
  end
end

app/helpers/requirements_helper.rb
module RequirementsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def task
    @task ||= Task.find(params[:id])
  end
end

app/views/dependencies/_dependency.html.erb
<%= render dependency.dependent_task %>

app/views/dependencies/create.html.erb
<h1>Dependencies#create</h1>
<p>Find me in app/views/dependencies/create.html.erb</p>

app/views/goals/_goal.html.erb
<div class="goal">
  <h2><%= goal.name %></h2>
  <%= render goal.tasks, {locals: {feature: true}} %>

  <div><input id="search"></input></div>
  <div id="results"></div>

  <h3>Next Steps</h3>
  <%= goal.next_tasks.map { |task| render task }.join("\n").html_safe  %>
</div>

    <script type="text/javascript">
      window.search.addEventListener('input', debounced(function (ev) {
        const request = fetchingHTML('/tasks/search?q=' + window.search.value);

        request.then(response => response.json()).then(function(results) {
          window.results.innerHTML = '';

          results.forEach(function (result) {
            const div = document.createElement('div');
            const task = document.createElement('task');
            const button = document.createElement('button');

            button.innerHTML = 'Add as requirement';

            task.innerHTML = result.html;
            div.appendChild(task);
            div.appendChild(button);

            window.results.appendChild(div);

            button.addEventListener('click', function (ev) {
              fetching("<%= project_goal_requirements_path(project, goal) %>", {
                method: 'POST',
                body: JSON.stringify({
                  task_id: JSON.parse(result.json).id
                })
              }).then(() => location.reload());
            });
          })
        });
      }));
    </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lodestar</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <span><b><%= link_to_unless_current("Lodestar", root_path) %></b></span>

      <% if notice.present? %>
        <span class="notice"><%= notice %></span>
      <% end %>

      <% if alert.present? %>
        <span class="alert"><%= alert %></span>
      <% end %>

      <span>
        <% if signed_in? %>
          <%= current_user.email %> | <%= link_to("Logout", destroy_session_path(current_user), method: :DELETE) %>
        <% end %>
      </span>
    </header>

    <%= yield %>
  </body>
</html>

app/views/projects/_project.html.erb
<div class="project">
  <h2><%= link_to_unless_current(project.name, project_path(project)) %></h2>
</div>

app/views/projects/index.html.erb
<h1>Projects</h1>
<%= link_to 'Create new', new_project_path %>
<%= render current_user.projects %>

app/views/projects/new.html.erb
<%= form_for(Project.new) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/projects/show.html.erb
<div class="project-show">
  <div class="controls">
  <h1><%= project.name %></h1>
    <h2>Goals</h2>

    <h3>Add new goal</h2>
    <%= form_for([ project, Goal.new ]) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.submit %>
    <% end %>

    <h2>Add new Task</h2>
    <%= form_for(Task.new) do |f| %>
      <div>
        <%= f.label :name %>
        <div><%= f.text_field :name %></div>
      </div>

      <div>
        <%= f.label :description %>
        <div><%= f.text_area :description, rows: 4, cols: 40 %></div>
      </div>

      <%= f.submit %>
    <% end %>
  </div>

  <div class="goals-inner">
    <%= render project.goals %>
  </div>
</div>

app/views/tasks/_task.html.erb
<div class="task">
  <h3 class="title"><%= link_to_unless_current("##{task.id}", task) %> <%= link_to_unless_current(task.name, task) %></h3>
  <p><%= task.description %></p>

  <div><%= task.completed ? "Completed" : "Todo" %></div>

  <%= link_to('Edit Task', edit_task_path(task)) %>

  <% if task.dependency_tasks.incomplete.empty? %>
    <%= link_to(task.completed ? 'Mark as incomplete' : 'Mark as completed', complete_task_path(task), method: :POST) %>
  <% else %>
    <%= task.dependency_count %> dependencies to complete
  <% end %>
</div>

app/views/tasks/edit.html.erb
<%= form_for(task) do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :completed %>
    <%= f.check_box :completed %>
  </div>

  <div>
    <%= f.label :archived %>
    <%= f.check_box :archived %>
  </div>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<div class="flex">
  <div class="tasks">
    <h1>Tasks</h1>

    <h2>Add new</h2>
    <%= form_for(Task.new) do |f| %>
      <div>
        <%= f.label :name %>
        <div><%= f.text_field :name %></div>
      </div>

      <div>
        <%= f.label :description %>
        <div><%= f.text_area :description, rows: 4, cols: 40 %></div>
      </div>

      <%= f.submit %>
    <% end %>

    <ul>
      <% Task.all.each do |task| %>
        <li>
          <%= link_to(task.name, task) %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="goals">
    <h1>Goals</h1>

    <div class="goals-inner">
      <%= render Goal.all %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<%= link_to 'Back to tasks list', tasks_path %>

<%= render task %>

<h2>Dependencies</h2>

<div>Add new dependency</div>
<div><input id="search"></input></div>
<div id="results"></div>

<script type="text/javascript">

const resolved_task_id = <%= task.id %>;

window.search.addEventListener('input', debounced(function (ev) {
  if (window.search.value === '') {
    window.results.innerHTML = '';
    return
  };

  const request = fetchingHTML('/tasks/search?q=' + window.search.value);

  // TODO - fix this shit
  request.then(response => response.json()).then(function(results) {
    window.results.innerHTML = '';

    results.forEach(function (result) {
      const div = document.createElement('div');
      const task = document.createElement('task');
      const button = document.createElement('button');

      button.innerHTML = 'Add as dependency';

      task.innerHTML = result.html;
      div.appendChild(task);
      div.appendChild(button);

      button.addEventListener('click', function () {
        const form = document.createElement('form');

        const request = fetching("/dependencies", {
          method: "POST",
          body: JSON.stringify({
            dependency: {
              resolved_task_id,
              dependent_task_id: JSON.parse(result.json).id
            }
          })
        });

        request.then(() => location.reload());
      });

      window.results.appendChild(div);
    });
  });
}, 150));
</script>

<%= render task.dependency_tasks.order(:completed) %>

<h2>Dependents</h2>

<%= render task.dependent_tasks %>